name_model: "vinai/phobert-base-v2" # uitnlp/visobert , vinai/phobert-base
max_length: 256

num_classes: 5
batch_size: 16
epochs: 25 # 20

device: "cuda"
seed: 32
isKaggle: False
key: ["AMBIENCE", "QUALITY", "PRICES", "LOCATION", "SERVICE"]

losses: 1 # 1: BCE, 2: CrossEntropy
model: 1 # 1: 3072 -> 4 || 2: 3072 -> 256 -> 4 + LayerNorm ||
drop_rate: [0.2, 0.3] # model 1: [0.2] # model 2: [0.2, 0.3] # model 3: [0.5]

optimizer: "Adam" # model 1: "Adam" # model 2: "AdamW"
lr: 0.0001 # model 1: 1e-4 # model 2: 1e-5

clip_grad_norm: False # model 2
scheduler: True
weights: []

T_max: 1356 # 1356 # model 1,2
eta_min: 0.00001 # model 1, 2
weight_decay: 0 # model 2

layer_norm: False
